#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#NelmioApiDocBundle:
#    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
#    prefix: /api/doc
app.swagger_ui:
      path: /api/doc
      methods: GET
      defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
api:
      path: /api
      controller: App\Controller\DefaultController::api
login_check:
    path: /login_check
    methods: [POST]
